"""Regenerate the cross-language test vectors.

Output is written UTF-8 and ASCII-only on purpose. Without an explicit encoding
Path.write_text() uses the platform default — cp1252 on Windows, UTF-8 on Linux —
so a file generated on one and regenerated on the other differs by mojibake and
the CI freshness check can never pass.

Outputs:
  common/python/tests/vectors/adpcm_ref.json   (Python regression lock)
  firmware/tests/host/vectors/proto_vectors.h  (C twin lock)

Run from the repo root:  python common/python/tests/gen_vectors.py
The C host tests re-derive the same values independently; if either implementation
drifts, its test suite fails against these committed artifacts.
"""

from __future__ import annotations

import json
import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from powersuit_proto import can_id, spi_frame  # noqa: E402
from powersuit_proto.adpcm import AdpcmState, decode, encode  # noqa: E402
from powersuit_proto.can_id import Cls, MsgType, Node  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[3]
JSON_OUT = pathlib.Path(__file__).parent / "vectors" / "adpcm_ref.json"
C_OUT = REPO / "firmware" / "tests" / "host" / "vectors" / "proto_vectors.h"

N_SAMPLES = 512


def test_signal(n: int) -> list[int]:
    out = []
    lcg = 0x2A5F_11E7
    for i in range(n):
        lcg = (lcg * 1103515245 + 12345) & 0x7FFF_FFFF
        noise = (lcg >> 16) % 1201 - 600
        s = (
            int(9000 * math.sin(2 * math.pi * 233.0 * i / 8000.0))
            + int(4000 * math.sin(2 * math.pi * 941.0 * i / 8000.0))
            + noise
        )
        out.append(max(-32768, min(32767, s)))
    return out


def spi_test_records(n: int) -> list[spi_frame.CanRecord]:
    return [
        spi_frame.CanRecord(
            id=can_id.pack(Cls.TELEM, 1 + (i % 6), Node.ORCH, MsgType.JOINT_STATE, i & 0xFF),
            bus=i % 2,
            dlc=8,
            ts_ms=1000 + i,
            data=bytes((i * 16 + j) & 0xFF for j in range(8)),
        )
        for i in range(n)
    ]


def c_array(name: str, ctype: str, values, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    body = "\n".join(lines)
    return f"static const {ctype} {name}[{len(values)}] = {{\n{body}\n}};\n"


def main() -> None:
    pcm = test_signal(N_SAMPLES)
    st = AdpcmState()
    enc = encode(st, pcm)
    dec = decode(AdpcmState(), enc)

    frame = spi_frame.build_frame(spi_frame.SPIF_MORE_PENDING, 42, spi_test_records(7))

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps(
            {
                "comment": "Generated by gen_vectors.py - do not edit by hand.",
                "adpcm": {
                    "pcm": pcm,
                    "encoded_hex": enc.hex(),
                    "decoded": dec,
                    "final_predictor": st.predictor,
                    "final_step_index": st.step_index,
                },
                "spi": {
                    "frame_hex": frame.hex(),
                    "flags": spi_frame.SPIF_MORE_PENDING,
                    "seq": 42,
                    "count": 7,
                },
            },
            indent=1,
        )
        + "\n",
        encoding="utf-8",
    )

    C_OUT.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "/* Generated by common/python/tests/gen_vectors.py - do not edit by hand.",
        " * Locks the C implementations to the Python twins. */",
        "#ifndef PROTO_VECTORS_H",
        "#define PROTO_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define PS_VEC_ADPCM_N {N_SAMPLES}",
        c_array("PS_VEC_ADPCM_PCM", "int16_t", pcm),
        c_array("PS_VEC_ADPCM_ENC", "uint8_t", list(enc)),
        c_array("PS_VEC_ADPCM_DEC", "int16_t", dec),
        f"#define PS_VEC_ADPCM_FINAL_PREDICTOR {st.predictor}",
        f"#define PS_VEC_ADPCM_FINAL_STEP_INDEX {st.step_index}",
        "",
        f"#define PS_VEC_SPI_FRAME_LEN {len(frame)}",
        c_array("PS_VEC_SPI_FRAME", "uint8_t", list(frame)),
        "#define PS_VEC_SPI_FLAGS 0x04u  /* SPIF_MORE_PENDING */",
        "#define PS_VEC_SPI_SEQ 42u",
        "#define PS_VEC_SPI_COUNT 7u",
        "",
        "#endif /* PROTO_VECTORS_H */",
    ]
    C_OUT.write_text("\n".join(header) + "\n", encoding="utf-8")
    print(f"wrote {JSON_OUT.relative_to(REPO)} and {C_OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
